FROM python:3.11.3-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE cassandre.dev_docker_settings

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
    build-essential \
    libpq-dev \
    git \
    nginx \
    curl \
    gnupg \
    build-essential \
    supervisor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Generate fr_FR.UTF-8 locale
RUN sed -i '/fr_FR.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

# Set fr_FR.UTF-8 as the default locale
ENV LANG fr_FR.UTF-8  
ENV LANGUAGE fr_FR:fr  
ENV LC_ALL fr_FR.UTF-8  

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements /app/requirements/
RUN pip install --upgrade pip && pip install -r requirements/dev.txt

# Copy project files
COPY . /app/
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf