---
  version: '3'
  services:
    web:
      profiles:
        - dev
      build: 
        context: .
        dockerfile: Dockerfile.dev
      command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      environment:
        - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
        - PYTHONDONTWRITEBYTECODE 1
        - PYTHONUNBUFFERED 1
        - DJANGO_SETTINGS_MODULE cassandre.dev_docker_settings
      depends_on:
        - db
        - redis
        - qdrant
        - minio
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
    minio:
      image: minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
      volumes:
        - minio-data:/data
      command: ["server", "--console-address", ":9001", "/data"]
    minio_mc:
      image: minio/mc:latest
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
        sleep 5;
        mc alias set minio http://minio:9000 minio minio123;
        "      
    qdrant:
      image: qdrant/qdrant:v1.1.2
      ports: 
        - "6334:6334"
        - "6333:6333"
      volumes:
        - qdrant-data:/qdrant/storage
    db:
      image: postgres:14
      ports: 
        - "5432:5432"
      environment: 
        - POSTGRES_PASSWORD=postgres
      volumes:
          - db-data:/var/lib/postgresql/data
      #command: ["postgres", "-c", "log_statement=all"]
    adminer:
      image: adminer
      depends_on:
        - db
      environment:
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DEFAULT_DB_DRIVER: pgsql
        ADMINER_DEFAULT_DB_HOST: db
        ADMINER_DESIGN: nette
        ADMINER_PLUGINS: tables-filter tinymce
      ports:
        - "9010:8080"    
    maildev:
      image: mailhog/mailhog
      environment:
        - MAILDEV_INCOMING_USER=caliste
        - MAILDEV_INCOMING_PASS=password
      ports:
        - "1080:8025"
        - "1025:1025"        
  volumes:
    db-data:
    qdrant-data:
    minio-data:
