# Generated by Django 4.2 on 2023-05-17 18:10

from django.db import migrations, models
import django.db.models.deletion

def create_default_category(apps, schema_editor):
    Category = apps.get_model('documents', 'Category')
    Category.objects.create(name="Documents", slug="documents")

def set_default_category(apps, schema_editor):
    Category = apps.get_model('documents', 'Category')
    Document = apps.get_model('documents', 'Document')
    default_category = Category.objects.get(name="Documents")
    for document in Document.objects.all():
        document.category = default_category
        document.save()



class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('prompt', models.TextField()),
                ('k', models.IntegerField(default=4)),
            ],
        ),
        migrations.RunPython(create_default_category),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.category'),
        ),
        migrations.RunPython(set_default_category),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='documents.category'),
        ),
    ]
