# Generated by Django 4.2.1 on 2023-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='query_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='correction',
            unique_together={('category', 'query_hash')},
        ),
        migrations.AddIndex(
            model_name='correction',
            index=models.Index(fields=['category', 'query_hash'], name='category_queryhash_idx'),
        ),
    ]
