# Generated by Django 4.2.1 on 2023-09-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20230527_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hints',
            field=models.TextField(blank=True, help_text='Hints to augment the context for the document.', null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='query_hash',
            field=models.CharField(default='default', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
