# Generated by Django 4.2.1 on 2023-10-23 17:36

from django.db import migrations, models
import os
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for document in Document.objects.all():
        # Extract the last part of the file path (i.e., the filename with extension)
        filename_with_extension = document.file.name.split("/")[-1]

        # Split the filename from its extension and take only the filename
        filename_without_extension = os.path.splitext(filename_with_extension)[0]

        # Set the slug using category slug and filename without extension
        document.slug = slugify(f"{document.category.slug}-{filename_without_extension}")
        document.save()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_hints_alter_correction_query_hash'),
    ]

    operations = [
        # Step 1: Add the slug field as nullable
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(editable=True, max_length=1024, unique=True, null=True),
        ),

        # Step 2: Populate the slugs
        migrations.RunPython(generate_slugs),

        # Step 3: Make the slug field non-nullable
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(editable=True, max_length=1024, unique=True, null=False),
        ),
    ]
