# Generated by Django 4.2.1 on 2023-10-23 17:40

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_slug_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to=documents.models.get_upload_path),
        ),
    ]
